image: golang:1.9.2
stages:
  - test
  - build-win
#  - build-darwin
#  - build-linux

before_script:
  - mkdir -p $GOPATH/src/github.com/iain17/decentralizer/
  - ln -s $CI_PROJECT_PATH $GOPATH/src/github.com/iain17/decentralizer/
#  - apt-get -y update
#  - apt-get -y install build-essential upx-ucl
#  - go get -v -u github.com/whyrusleeping/gx-go
#  - go get -v -u github.com/golang/dep/cmd/dep
  - make install

test:
  stage: test
  script:
    - go test -v -cover ./...

build-win:
  stage: build-win
  artifacts:
    paths:
    - bin/win/adna.exe
  script:
    - make build-win