image: golang:1.9.2
stages:
  - test
  - build

variables:
  REPO_BASE: github.com/iain17/decentralizer

before_script:
  - apt-get -y update
  - apt-get -y install build-essential upx-ucl
  - mkdir -p $GOPATH/src/$REPO_BASE
  - cp -r $CI_PROJECT_DIR/* $GOPATH/src/$REPO_BASE
  - chmod +x $GOPATH/src/$REPO_BASE/build.sh
  - cd $GOPATH/src/$REPO_BASE

test:
  stage: test
  script:
    - cd $GOPATH/src/$REPO_BASE
    - go test -cover ./...

build:
  stage: build
  artifacts:
    untracked: true
    paths:
      - binaries/
  only:
    - master
    - develop
  script:
    - cd $GOPATH/src/$REPO_BASE
    - ./build.sh
    - mkdir -p $CI_PROJECT_DIR/binaries
    - cp -r $GOPATH/src/$REPO_BASE/bin/* $CI_PROJECT_DIR/binaries