image: golang:1.9.2
stages:
  - test
  - build

variables:
  REPO_BASE: github.com/iain17/decentralizer

before_script:
  - export REPO_BASE=$GOPATH/src/$REPO_BASE
  - apt-get -y update
  - apt-get -y install build-essential upx-ucl
  - mkdir -p $REPO_BASE
  - cp -r $CI_PROJECT_DIR/* $REPO_BASE
  - chmod +x $REPO_BASE/build.sh
  - cd $REPO_BASE
  - go get -u github.com/iain17/gorep
  - gorep -banned="iain17,github" -path $REPO_BASE
  - gorep -banned="iain17,github" -path $REPO_BASE
  - mkdir updateDir && cd updateDir && cd .. && rm -rf updateDir
  - export REPO_BASE=$(pwd)
  - echo $REPO_BASE

test:
  stage: test
  script:
    - cd $REPO_BASE
    - go test -cover ./...

build:
  stage: build
  artifacts:
    paths:
      - binaries/
  only:
    - master
    - develop
  script:
    - cd $REPO_BASE
    - ./build.sh
    - mkdir -p $CI_PROJECT_DIR/binaries
    - cp -r $REPO_BASE/bin/* $CI_PROJECT_DIR/binaries