image: golang:1.9.2
stages:
  - test
  - build
  - pack

variables:
  REPO_BASE: github.com/iain17/decentralizer

cache:
  key: "$CI_COMMIT_SHA"
  paths:
    - $CI_PROJECT_DIR/bin

before_script:
  - export REPO_BASE=$GOPATH/src/$REPO_BASE
  - mkdir -p $REPO_BASE
  - cp -r $CI_PROJECT_DIR/* $REPO_BASE
  - cd $REPO_BASE

test:
  stage: test
  script:
    - cd $REPO_BASE
    - make test

build:
  stage: build
  artifacts:
    name: "$CI_COMMIT_REF_NAME ADNA @$CI_COMMIT_SHA (unpacked)"
    paths:
      - bin/
  script:
    - go get -u github.com/iain17/gorep
    - gorep -banned="iain17,decentralizer" -path $GOPATH/src/ > /dev/null 2>&1
    - mkdir updateDir && cd updateDir && cd .. && rm -rf updateDir
    - export REPO_BASE=$(pwd)
    - echo $REPO_BASE

    - cd $REPO_BASE
    - chmod +x $REPO_BASE/build.sh
    - ./build.sh
    - cp -r $REPO_BASE/bin/* $CI_PROJECT_DIR/bin

pack:
  stage: pack
  only:
    - master
    - develop
  artifacts:
    name: "$CI_COMMIT_REF_NAME ADNA @$CI_COMMIT_SHA (packed)"
    paths:
      - bin/
  script:
    - apt-get -y update
    - apt-get -y install upx-ucl

    - ls $CI_PROJECT_DIR/bin/
    - cp -r $CI_PROJECT_DIR/bin/* $REPO_BASE/bin/
    - cd $REPO_BASE
    - chmod +x $REPO_BASE/pack.sh
    - ./pack.sh
    - mkdir -p $CI_PROJECT_DIR/packed
    - cp -r $REPO_BASE/bin/* $CI_PROJECT_DIR/bin